/**
 * Login + Register copy. Same shape as landingStrings but kept in its own
 * module so the auth pages can stay independent of the marketing page.
 */
export const AUTH_STRINGS = {
  en: {
    common: {
      brand: 'MedicaLLM',
      heroTitleA: 'Your Intelligent',
      heroTitleB: 'Medical Companion',
      heroSubtitle:
        'Access comprehensive drug information, check interactions, search published research, and get evidence-based answers — all powered by AI.',
      featureEvidenceTitle: 'Evidence-Based',
      featureEvidenceDesc: 'Every claim is backed by DrugBank or PubMed sources you can verify.',
      featureSafetyTitle: 'Safety Focused',
      featureSafetyDesc: 'Real-time interaction checking helps prevent adverse drug events.',
      featureFastTitle: 'Built For Speed',
      featureFastDesc: 'Streaming answers and typo-tolerant search — designed for clinical workflows.',
      backHome: 'Back to home',
    },
    login: {
      title: 'Welcome back',
      subtitle: 'Sign in to continue your medical research.',
      emailLabel: 'Email',
      emailPlaceholder: 'you@example.com',
      passwordLabel: 'Password',
      passwordPlaceholder: 'Enter your password',
      submit: 'Sign in',
      submitting: 'Signing in…',
      forgot: 'Forgot password?',
      noAccount: "Don't have an account?",
      createOne: 'Create one',
    },
    forgot: {
      title: 'Forgot password?',
      subtitle: 'Enter your email and we will send you a reset code.',
      emailLabel: 'Email',
      emailPlaceholder: 'you@example.com',
      submit: 'Send reset code',
      submitting: 'Sending…',
      backToLogin: 'Back to sign in',
    },
    reset: {
      title: 'Reset your password',
      subtitle: 'Enter the code we sent to your email and choose a new password.',
      codeLabel: 'Verification code',
      codePlaceholder: '6-digit code',
      newPasswordLabel: 'New password',
      newPasswordPlaceholder: 'Choose a new password',
      submit: 'Reset password',
      submitting: 'Resetting…',
      backToLogin: 'Back to sign in',
    },
    register: {
      title: 'Create your account',
      subtitle: 'Free 20 queries a day, no credit card required.',
      nameLabel: 'Full name',
      namePlaceholder: 'Jane Doe',
      emailLabel: 'Email',
      emailPlaceholder: 'you@example.com',
      passwordLabel: 'Password',
      passwordPlaceholder: 'Choose a strong password',
      accountTypeLabel: 'I am a…',
      accountUser: 'General user',
      accountDoctor: 'Healthcare professional',
      accountPatient: 'Patient',
      submit: 'Create account',
      submitting: 'Creating account…',
      haveAccount: 'Already have an account?',
      signInLink: 'Sign in',
    },
    verify: {
      title: 'Check your email',
      subtitle: 'We sent a 6-digit code to your inbox. Enter it below to finish signing up.',
      codeLabel: 'Verification code',
      codePlaceholder: '6-digit code',
      submit: 'Verify and sign in',
      submitting: 'Verifying…',
      back: 'Back to registration',
    },
    passwordRules: {
      heading: 'Password must include:',
      uppercase: '1 uppercase letter',
      lowercase: '1 lowercase letter',
      number: '1 number',
      special: '1 special character',
      length: 'At least 8 characters',
    },
  },

  tr: {
    common: {
      brand: 'MedicaLLM',
      heroTitleA: 'Akıllı',
      heroTitleB: 'Tıbbi Yardımcınız',
      heroSubtitle:
        'Kapsamlı ilaç bilgilerine ulaşın, etkileşimleri kontrol edin, yayımlanmış araştırmaları tarayın ve yapay zekâ destekli kanıta dayalı yanıtlar alın.',
      featureEvidenceTitle: 'Kanıta Dayalı',
      featureEvidenceDesc: 'Her ifade DrugBank veya PubMed kaynaklarına dayanır, doğrulayabilirsiniz.',
      featureSafetyTitle: 'Güvenlik Odaklı',
      featureSafetyDesc: 'Gerçek zamanlı etkileşim kontrolü ile advers ilaç olaylarını önleyin.',
      featureFastTitle: 'Hızlı',
      featureFastDesc: 'Akan yanıtlar ve hata toleranslı arama — klinik akış için tasarlandı.',
      backHome: 'Anasayfaya dön',
    },
    login: {
      title: 'Tekrar hoş geldiniz',
      subtitle: 'Tıbbi araştırmanıza devam etmek için giriş yapın.',
      emailLabel: 'E-posta',
      emailPlaceholder: 'siz@ornek.com',
      passwordLabel: 'Şifre',
      passwordPlaceholder: 'Şifrenizi girin',
      submit: 'Giriş yap',
      submitting: 'Giriş yapılıyor…',
      forgot: 'Şifremi unuttum',
      noAccount: 'Hesabınız yok mu?',
      createOne: 'Hesap oluştur',
    },
    forgot: {
      title: 'Şifremi unuttum',
      subtitle: 'E-postanızı girin, sıfırlama kodunu gönderelim.',
      emailLabel: 'E-posta',
      emailPlaceholder: 'siz@ornek.com',
      submit: 'Sıfırlama kodu gönder',
      submitting: 'Gönderiliyor…',
      backToLogin: 'Girişe dön',
    },
    reset: {
      title: 'Şifrenizi sıfırlayın',
      subtitle: 'E-postanıza gelen kodu girin ve yeni şifrenizi seçin.',
      codeLabel: 'Doğrulama kodu',
      codePlaceholder: '6 haneli kod',
      newPasswordLabel: 'Yeni şifre',
      newPasswordPlaceholder: 'Yeni şifre seçin',
      submit: 'Şifreyi sıfırla',
      submitting: 'Sıfırlanıyor…',
      backToLogin: 'Girişe dön',
    },
    register: {
      title: 'Hesap oluştur',
      subtitle: 'Günde 20 sorgu ücretsiz, kredi kartı gerekmez.',
      nameLabel: 'Ad soyad',
      namePlaceholder: 'Ad Soyad',
      emailLabel: 'E-posta',
      emailPlaceholder: 'siz@ornek.com',
      passwordLabel: 'Şifre',
      passwordPlaceholder: 'Güçlü bir şifre seçin',
      accountTypeLabel: 'Hesap türü',
      accountUser: 'Genel kullanıcı',
      accountDoctor: 'Sağlık profesyoneli',
      accountPatient: 'Hasta',
      submit: 'Hesap oluştur',
      submitting: 'Oluşturuluyor…',
      haveAccount: 'Zaten hesabınız var mı?',
      signInLink: 'Giriş yap',
    },
    verify: {
      title: 'E-postanızı kontrol edin',
      subtitle: 'Gelen kutunuza 6 haneli bir kod gönderdik. Kaydı tamamlamak için aşağıya girin.',
      codeLabel: 'Doğrulama kodu',
      codePlaceholder: '6 haneli kod',
      submit: 'Doğrula ve giriş yap',
      submitting: 'Doğrulanıyor…',
      back: 'Kayda geri dön',
    },
    passwordRules: {
      heading: 'Şifre şunları içermelidir:',
      uppercase: '1 büyük harf',
      lowercase: '1 küçük harf',
      number: '1 rakam',
      special: '1 özel karakter',
      length: 'En az 8 karakter',
    },
  },
};
